project_id = "sjiclodfxmwrdtobnrbt"
[functions.contact-seller]
enabled = true
verify_jwt = true
import_map = "supabase/functions/contact-seller/deno.json"
entrypoint = "supabase/functions/contact-seller/index.ts"

[functions.send-test-email]
enabled = true
verify_jwt = true
entrypoint = "supabase/functions/send-test-email/index.ts"
